### ISSUE TITLE
demo çalışmıyor

### ISSUE THREAD

**Issue by huseyinozkilic** [aligoren/carbon-panel#5]

**Comment by aligoren** [comment]
Su anda tekrar kontrol ettiniz mi? Rica etsem edebilir misiniz?

https://aligoren.github.io/carbon-panel

GitHub pages sanirim 1-2 saat geciktirdi render etmeyi.

**Comment by huseyinozkilic** [comment]
şimdi baktım fakat alt sayfalara geçmiyor, konsola bir hata da düşmüyor

**Comment by aligoren** [comment]
şu an o sayfaların tamamı yok tamamlandıkça ekleyeceğim. Status kismina o nedenle WIP yazmistim aslinda. Components ve alttaki sayfalar eksik :)

**Comment by huseyinozkilic** [comment]
şimdi anlaşıldı, o yazıyı hiç görmemişim :)

**Comment by aligoren** [comment]
Problem degilse issue'yu kapatiyorum sorun olursa yine acarsiniz :)
